name: Publish
on:
# later, uncomment this and possibly comment out the manual trigger
#  push:
#   branches:
#      - "main"
  workflow_dispatch

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: main
      - uses: actions/checkout@v2
        with:
          ref: stable
      - name: Merge
        run: |
          git merge main
          git push
